In [17]:
import pandas as pd
import numpy as np

from openpyxl import load_workbook

In [12]:
wb = load_workbook("have_fun.xlsx", data_only=True)


def decode_title(title: str) -> str:
    if not isinstance(title, str):
        return title

    try:
        return title.encode("latin1").decode("cp1251")
    except (UnicodeDecodeError, UnicodeEncodeError):
        return title


analysis_table = []
for sheet_name in wb.sheetnames:
    sheet = wb[sheet_name]
    analysis_table.append({
        "title": sheet.title,
        "fixed_title": decode_title(sheet.title),
        "state": sheet.sheet_state,
        "max_row": sheet.max_row,
        "max_column": sheet.max_column,
        "dimension": sheet.calculate_dimension()
    })

print(analysis_table)

[{'title': 'Ëèñò1', 'fixed_title': 'Лист1', 'state': 'visible', 'max_row': 125125, 'max_column': 10, 'dimension': 'A1:J125125'}, {'title': 'Лист1', 'fixed_title': 'Лист1', 'state': 'visible', 'max_row': 1, 'max_column': 1, 'dimension': 'A1:A1'}, {'title': 'ÌÀÈ', 'fixed_title': 'МАИ', 'state': 'visible', 'max_row': 1, 'max_column': 1, 'dimension': 'A1:A1'}, {'title': 'ýòî', 'fixed_title': 'это', 'state': 'visible', 'max_row': 1, 'max_column': 1, 'dimension': 'A1:A1'}, {'title': 'ÿ', 'fixed_title': 'я', 'state': 'visible', 'max_row': 1, 'max_column': 1, 'dimension': 'A1:A1'}, {'title': '!', 'fixed_title': '!', 'state': 'visible', 'max_row': 1, 'max_column': 1, 'dimension': 'A1:A1'}, {'title': 'Ëèñò2_ñòðîêîâûå_NaN_âûáðîñû', 'fixed_title': 'Лист2_строковые_NaN_выбросы', 'state': 'hidden', 'max_row': 125170, 'max_column': 25, 'dimension': 'A1:Y125170'}, {'title': 'Ëèñò3_ñìåøàííûå_òèïû', 'fixed_title': 'Лист3_смешанные_типы', 'state': 'hidden', 'max_row': 122737, 'max_column': 10, 'dimension': 'A1:J122737'}]

4 названия листов образуют "МАИ это я!". 5 листов пустые + 3 листа заполненные, как и говорилось в ТЗ. Причем 2 листа с данными скрыты.

In [18]:
for sheet_name in wb.sheetnames:
    sheet = wb[sheet_name]

    if sheet.max_row > 1 and sheet.max_column > 1:
        print(f"Original title: {sheet.title}")
        print(f"Decoded title: {decode_title(sheet.title)}")
        print(f"Size: {sheet.max_row} x {sheet.max_column}")

        rows = []
        for row in sheet.iter_rows(min_row=1, max_row=5, values_only=True):
            decoded_row = [decode_title(i) for i in row]
            rows.append(decoded_row)

        df = pd.DataFrame(rows)
        display(df)

Original title: Ëèñò1
Decoded title: Лист1
Size: 125125 x 10

,0,1,2,3,4,5,6,7,8,9
0,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,weathercode,wind_speed_10m,surface_pressure,ds,city
1,3.8,82.0,0.0,0.0,0.0,3.0,19.1,1010.0,2020-01-31 02:00:00,Геленджик
2,-3.0,70.0,0.0,0.0,0.0,3.0,24.0,981.900024,2025-02-28 09:00:00,Благовещенск
3,-1.3,86.0,0.0,0.0,0.0,2.0,8.8,1021.200012,2022-01-03 02:00:00,Геленджик
4,19.299999,49.0,0.0,0.0,0.0,0.0,22.799999,1016.200012,2020-09-17 06:00:00,Геленджик

Original title: Ëèñò2_ñòðîêîâûå_NaN_âûáðîñû
Decoded title: Лист2_строковые_NaN_выбросы
Size: 125170 x 25

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,weathercode,wind_speed_10m,surface_pressure,ds,city,...,None,None,None,None,None,None,None,None,None,None
1,-6.5,92.0,0.0,0.0,0.0,3.0,10.8,1000.5,2019-01-01 00:00:00,Москва,...,None,None,None,None,None,None,None,None,None,None
2,-6.8,92.0,0.0,0.0,0.0,3.0,10.5,1000.299988,2019-01-01 01:00:00,Москва,...,None,None,None,None,None,None,None,None,None,None
3,-6.8,92.0,0.0,0.0,0.0,3.0,10.8,1000.0,2019-01-01 02:00:00,Москва,...,None,None,None,None,None,None,None,None,None,None
4,-5.8,93.0,0.0,0.0,0.0,3.0,12.2,999.299988,2019-01-01 03:00:00,Москва,...,None,None,None,None,None,None,None,None,None,None

Original title: Ëèñò3_ñìåøàííûå_òèïû
Decoded title: Лист3_смешанные_типы
Size: 122737 x 10

,0,1,2,3,4,5,6,7,8,9
0,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,weathercode,wind_speed_10m,surface_pressure,ds,city
1,-1.8,85.0,0.0,0.0,0.0,3.0,23.5,1015.200012,2019-01-01 00:00:00,Санкт-Петербург
2,-1.9,83.0,0.0,0.0,0.0,3.0,26.0,1013.200012,2019-01-01 01:00:00,Санкт-Петербург
3,-2.0,85.0,0.0,0.0,0.0,3.0,26.200001,1011.700012,2019-01-01 02:00:00,Санкт-Петербург
4,-2.3,86.0,0.0,0.0,0.0,3.0,26.9,1009.900024,2019-01-01 03:00:00,Санкт-Петербург

Мы видим, что 1 и 3 таблицы идентичны по количеству и названий колонк, а вот 2 таблица отличается тем, что в ней на 15 столбцов больше. Вряд ли openpyxl глупа и просто так считает пустые колонки. Нужно будет проверить, что есть в этой области

In [24]:
sheet_name = "Ëèñò2_ñòðîêîâûå_NaN_âûáðîñû"
sheet = wb[sheet_name]

for col_ind in range(11, sheet.max_column + 1):
    non_empty = 0
    first = last = None

    for row_ind in range(1, sheet.max_row):
        cell = sheet.cell(row=row_ind, column=col_ind).value

        if cell is not None:
            non_empty += 1
            if first is None:
                first = row_ind
            last = row_ind

    print(f"Col {col_ind}: непустых значений - {non_empty}, first - {first}, last - {last}")

Col 11: непустых значений - 0, first - None, last - None
Col 12: непустых значений - 1, first - 84029, last - 84029
Col 13: непустых значений - 1, first - 84029, last - 84029
Col 14: непустых значений - 1, first - 84029, last - 84029
Col 15: непустых значений - 41, first - 84029, last - 84069
Col 16: непустых значений - 148, first - 15, last - 84069
Col 17: непустых значений - 149, first - 15, last - 84069
Col 18: непустых значений - 148, first - 15, last - 84069
Col 19: непустых значений - 149, first - 15, last - 84069
Col 20: непустых значений - 149, first - 15, last - 84069
Col 21: непустых значений - 149, first - 15, last - 84069
Col 22: непустых значений - 108, first - 15, last - 122
Col 23: непустых значений - 108, first - 15, last - 122
Col 24: непустых значений - 108, first - 15, last - 122
Col 25: непустых значений - 107, first - 15, last - 122

Дальше я хочу посмотреть какие вообще могут быть данные в этих диапазонах

In [33]:
def show_range(sheet, min_row, max_row, min_col, max_col):
    rows = []

    for row in sheet.iter_rows(
        min_row=min_row,
        max_row=max_row,
        min_col=min_col,
        max_col=max_col,
        values_only=True
    ):
        decoded_row = [decode_title(i) for i in row]
        rows.append(decoded_row)

    return pd.DataFrame(rows)


display(show_range(sheet, 84029, 84029, 12, 14))
display(show_range(sheet, 84029, 84039, 15, 15))
display(show_range(sheet, 15, 25, 16, 25))

                0                     1              2
0  temperature_2m  relative_humidity_2m  precipitation

       0
0   rain
1    0.0
2    0.0
3    0.0
4    0.0
5    0.2
6    0.7
7    1.5
8    1.8
9    0.5
10   0.5

,0,1,2,3,4,5,6,7,8,9
0,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,weathercode,wind_speed_10m,surface_pressure,ds,city
1,-0.4,66.0,0.0,0.0,0.0,1.0,9.4,1025.099976,2022-11-11 07:00:00,Находка
2,0.1,67.0,0.0,0.0,0.0,2.0,7.1,1025.099976,2022-11-11 08:00:00,Находка
3,2.2,64.0,0.0,0.0,0.0,3.0,7.3,1025.599976,2022-11-11 09:00:00,Находка
4,3.9,63.0,0.0,0.0,0.0,3.0,6.6,1026.199951,2022-11-11 10:00:00,Находка
5,5.3,61.0,0.0,0.0,0.0,3.0,2.0,1026.0,2022-11-11 11:00:00,Находка
6,6.8,62.0,0.0,0.0,0.0,3.0,3.1,1025.699951,2022-11-11 12:00:00,Находка
7,8.2,56.0,0.0,0.0,0.0,3.0,6.4,1024.699951,2022-11-11 13:00:00,Находка
8,8.9,53.0,0.0,0.0,0.0,3.0,6.1,1023.799988,2022-11-11 14:00:00,Находка
9,8.4,58.0,0.0,0.0,0.0,3.0,7.6,1023.299988,2022-11-11 15:00:00,Находка
10,8.3,62.0,0.0,0.0,0.0,3.0,6.9,1022.900024,2022-11-11 16:00:00,Находка

In [45]:
def missing_values(val):
    missing_markers = {
        "",
        "?",
        "нет данных",
        "NA",
        "NAN",
        "NaN",
        "nan",
        "n/a",
        "null",
        "NULL",
        "---",
    }

    if val is None or pd.isna(val) or (isinstance(val, str) and decode_title(val).strip() in missing_markers):
        return True
    return False


block = show_range(sheet, 15, 122, 16, 25)
block_header = block.iloc[0].tolist()
block_data = block.iloc[1:].copy()
block_data.columns = block_header

print(f"Колонки:\n{block_header}\n")
print("Пропуски:\n")

for col in block_data.columns:
    missing_amount = block_data[col].map(missing_values).sum()
    print(f"{col}: {missing_amount}")

print(f"\nКоличество уникальных городов:\n{block_data['city'].value_counts(dropna=False)}\n")
print(f"Самая маленькая дата: {block_data['ds'].min()}\n")
print(f"Самая большая дата: {block_data['ds'].max()}\n")
print("Последние строки:")
display(block_data.tail())

Колонки:
['temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'snowfall', 'weathercode', 'wind_speed_10m', 'surface_pressure', 'ds', 'city']

Пропуски:

temperature_2m: 1
relative_humidity_2m: 0
precipitation: 3
rain: 0
snowfall: 0
weathercode: 0
wind_speed_10m: 0
surface_pressure: 0
ds: 0
city: 1

Количество уникальных городов:
city
Находка          40
Геленджик        33
Благовещенск     31
NaN               1
Благовещенскк     1
Геленджикк        1
Name: count, dtype: int64

Самая маленькая дата: 2019-03-02 19:00:00

Самая большая дата: 2025-12-31 23:00:00

Последние строки:

,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,weathercode,wind_speed_10m,surface_pressure,ds,city
103,14.9,53.0,0.0,0.0,0.0,0.0,14.0,992.5,2021-09-16 20:00:00,Благовещенск
104,-24.5,78.0,0.0,0.0,0.0,0.0,7.6,1015.200012,2022-01-22 01:00:00,Благовещенск
105,7.6,73.0,0.0,0.0,0.0,0.0,2.0,1019.0,2025-01-10 06:00:00,Геленджик
106,13.9,85.0,0.0,0.0,0.0,0.0,12.9,1007.5,2025-03-30 06:00:00,Геленджик
107,-17.6,68.0,0.0,0.0,0.0,0.0,3.4,1000.299988,2023-01-30 16:00:00,Благовещенск

Проверяемая область содержит полноценные погодные данные, однако это не непрерывный временной ряд (строки относятся к разным датам и городам). Вероятно эти строки понадобятся для восстановления исходной таблицы

In [50]:
block = show_range(sheet, 84029, 84069, 12, 21)

block_header = block.iloc[0].tolist()
block_data = block.iloc[1:].copy()
block_data.columns = block_header

print(f"Колонки:\n{block_header}\n")
print("Пропуски:\n")

for col in block_data.columns:
    missing_amount = block_data[col].map(missing_values).sum()
    print(f"{col}: {missing_amount}")

Колонки:
['temperature_2m', 'relative_humidity_2m', 'precipitation', 'rain', 'snowfall', 'weathercode', 'wind_speed_10m', 'surface_pressure', 'ds', 'city']

Пропуски:

temperature_2m: 40
relative_humidity_2m: 40
precipitation: 40
rain: 0
snowfall: 0
weathercode: 0
wind_speed_10m: 0
surface_pressure: 0
ds: 0
city: 0

Фрагмент в строках 84029-84069 и колонках 12-21 имеет правильные заголовки погодной таблицы, но в нем полностью отсутствуют значения сразу трех колонок, одна из них - целевая переменная темпы, поэтому такие данные непригодны для обучения модели

In [55]:
def expand_df(sheet, min_row, max_row, min_col, max_col, source_type):
    block = show_range(sheet, min_row, max_row, min_col, max_col)
    block["type"] = source_type

    return block


sheet1 = wb["Ëèñò1"]
sheet2 = wb["Ëèñò2_ñòðîêîâûå_NaN_âûáðîñû"]
sheet3 = wb["Ëèñò3_ñìåøàííûå_òèïû"]

headers = show_range(sheet1, 1, 1, 1, 10).iloc[0].tolist() + ["source_type"]
all_data = [
    expand_df(sheet1, 2, sheet1.max_row, 1, 10, "main"),
    expand_df(sheet2, 2, sheet2.max_row, 1, 10, "main"),
    expand_df(sheet2, 16, 122, 16, 25, "recovered"),
    expand_df(sheet3, 2, sheet3.max_row, 1, 10, "main")
]

df = pd.concat(all_data, ignore_index=True)
df.columns = headers

print(f"Размер: {df.shape}")
display(df.head())
display(df.tail())

Размер: (373136, 11)

,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,weathercode,wind_speed_10m,surface_pressure,ds,city,source_type
0,3.8,82.0,0.0,0.0,0.0,3.0,19.1,1010.000000,2020-01-31 02:00:00,Геленджик,main
1,-3.0,70.0,0.0,0.0,0.0,3.0,24.0,981.900024,2025-02-28 09:00:00,Благовещенск,main
2,-1.3,86.0,0.0,0.0,0.0,2.0,8.8,1021.200012,2022-01-03 02:00:00,Геленджик,main
3,19.299999,49.0,0.0,0.0,0.0,0.0,22.799999,1016.200012,2020-09-17 06:00:00,Геленджик,main
4,9.6,89.0,0.0,0.0,0.0,0.0,8.8,1024.400024,2025-04-16 05:00:00,Геленджик,main

,temperature_2m,relative_humidity_2m,precipitation,rain,snowfall,weathercode,wind_speed_10m,surface_pressure,ds,city,source_type
373131,2.5,84.0,0.3,0.2,0.07,71.0,5.5,1005.099976,2025-12-31 19:00:00,Сочи,main
373132,2.6,79.0,0.1,0.1,0.00,51.0,8.4,1006.099976,2025-12-31 20:00:00,Сочи,main
373133,2.2,79.0,0.2,0.1,0.07,71.0,5.3,1006.099976,2025-12-31 21:00:00,Сочи,main
373134,1.4,81.0,0.0,0.0,0.00,3.0,4.9,1007.099976,2025-12-31 22:00:00,Сочи,main
373135,1.5,75.0,0.0,0.0,0.00,3.0,6.7,1008.099976,2025-12-31 23:00:00,Сочи,main

In [66]:
display(df.dtypes)
print()
display(df["city"].value_counts(dropna=True))

temperature_2m                  object
relative_humidity_2m           float64
precipitation                   object
rain                           float64
snowfall                       float64
weathercode                     object
wind_speed_10m                  object
surface_pressure               float64
ds                      datetime64[us]
city                               str
source_type                        str
dtype: object

city
Благовещенск       61690
Геленджик          61620
Санкт-Петербург    61368
Москва             61364
Сочи               61364
Находка            61357
Геленджикк           249
БЛАГОВЕЩЕНСК         245
Геленджи             242
благовещенск         239
Благовещенскк        231
геленджик            228
Благовещенс          226
ГЕЛЕНДЖИК            220
Сычи                   2
Мосва                  1
Счи                    1
Соч                    1
Name: count, dtype: int64